- name: test cmd source plugin with stdout
  hosts: localhost

  sources:
    - name: Run Go program executable/binary file
      nleiva.eda.cmd:
        command: "cd ansible-eda-go && ./closed-loop"
        repository: "https://github.com/nleiva/ansible-eda-go"
        send_output: true
        deserialize: false

  rules:
    - name: match cmd event
      condition: event.cmd is defined
      action:
        debug:
          msg: "{{ event.cmd }}"
