- name: test cmd source plugin with stdout
  hosts: localhost

  sources:
    - name: Run Go program executable/binary file
      nleiva.eda.cmd:
        command: git clone --quiet https://github.com/nleiva/ansible-eda-go; cd ansible-eda-go; ./main
        send_output: true
        deserialize: false

  rules:
    - name: match cmd event
      condition: event.cmd is defined
      action:
        debug:
          msg: "{{ event.cmd }}"

      # throttle:
      #   once_within: 5 minutes
      #   group_by_attributes:
      #     - event.cmd.failed
      # action:
      #   run_job_template:
      #     name: "Demo Job Template"
      #     organization: "Default"
      #     # Need JT prompt-on-launch for the below to work!
      #     job_args:
      #       extra_vars:
      #         device: '{{ event.cmd.device}}'