- name: test cmd source plugin with stdout
  hosts: localhost

  sources:
    - name: Run Go program executable/binary file
      nleiva.eda.cmd:
        command: ./main
        send_output: true

  rules:
    - name: match cmd event
      condition: event.cmd.failed == true and event.cmd.device == "sandbox-iosxe-latest-1.cisco.com"
      action:
        debug:
          msg: "sandbox-iosxe-latest-1.cisco.com FAILED"

      # throttle:
      #   once_within: 5 minutes
      #   group_by_attributes:
      #     - event.cmd.failed
      # action:
      #   run_job_template:
      #     name: "Demo Job Template"
      #     organization: "Default"
      #     # Need JT prompt-on-launch for the below to work!
      #     job_args:
      #       extra_vars:
      #         device: '{{ event.cmd.device}}'